<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2018sp1

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="xs">
    <xsl:output method="xml" encoding="UTF-8" indent="yes"/>
    <xsl:template match="/">
        <OrderRetrieveRQ Version="17.2">
            <xsl:attribute name="TransactionIdentifier">
                <xsl:value-of select="Request/Context/correlationID"/>
            </xsl:attribute>
            <xsl:attribute name="CorrelationID">
                <xsl:value-of select="Request/Context/correlationID"/>
            </xsl:attribute>
            <PointOfSale>
                <Location>
                    <CountryCode>FR</CountryCode>
                    <CityCode>NCE</CityCode>
                </Location>
            </PointOfSale>
            <Document id="document"/>
            <Party>
                <Sender>
                    <TravelAgencySender>
                        <Name>
                            <xsl:value-of select="Request/TravelAgency/Name"/>
                        </Name>
                        <PseudoCity>AH9D</PseudoCity>
                        <IATA_Number>
                            <xsl:value-of select="Request/TravelAgency/IATA_Number"/>
                        </IATA_Number>
                        <AgencyID>
                            <xsl:value-of select="Request/TravelAgency/IATA_Number"/>
                        </AgencyID>
                        <AgentUser>
                            <AgentUserID>xmluser001</AgentUserID>
                        </AgentUser>
                    </TravelAgencySender>
                </Sender>
            </Party>
            <Query>
                <Filters>
                    <OrderID>
                        <xsl:attribute name="Owner">
                            <xsl:value-of select="Request/Context/Retailer/code"/>
                        </xsl:attribute>
                        <xsl:value-of select="Request/bookingSourceInfo/rloc"/>
                    </OrderID>
                </Filters>
            </Query>
        </OrderRetrieveRQ>
    </xsl:template>
</xsl:stylesheet>
