<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2019

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="xs">
<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
<xsl:template match="/">
<xsl:variable name="var1_initial" select="."/>
<OrderCancelRQ>
<xsl:attribute name="Version">17.2</xsl:attribute>
<xsl:for-each select="Request/Context/correlationID">
<xsl:variable name="var2_cur" select="."/>
<xsl:attribute name="CorrelationID">
<xsl:value-of select="."/>
</xsl:attribute>
</xsl:for-each>
<PointOfSale>
<Location>
<CountryCode>
<xsl:value-of select="'IN'"/>
</CountryCode>
<CityCode>
<xsl:value-of select="'BLR'"/>
</CityCode>
</Location>
</PointOfSale>
<Document>
<xsl:attribute name="id">document</xsl:attribute>
</Document>
<Party>
<Sender>
<xsl:for-each select="Request">
<xsl:variable name="var3_cur" select="."/>
<TravelAgencySender>
<Name>
<xsl:value-of select="TravelAgency/Name"/>
</Name>
<PseudoCity>
<xsl:value-of select="'AH9D'"/>
</PseudoCity>
<xsl:for-each select="TravelAgency/IATA_Number">
<xsl:variable name="var4_cur" select="."/>
<IATA_Number>
<xsl:value-of select="."/>
</IATA_Number>
</xsl:for-each>
<xsl:for-each select="TravelAgency/IATA_Number">
<xsl:variable name="var5_cur" select="."/>
<AgencyID>
<xsl:value-of select="."/>
</AgencyID>
</xsl:for-each>
<AgentUser>
<AgentUserID>
<xsl:value-of select="'xmluser001'"/>
</AgentUserID>
</AgentUser>
</TravelAgencySender>
</xsl:for-each>
</Sender>
</Party>
<Query>
<Order>
<xsl:for-each select="Request/bookingSourceInfo/rloc">
<xsl:variable name="var6_cur" select="."/>
<xsl:attribute name="OrderID">
<xsl:value-of select="."/>
</xsl:attribute>
</xsl:for-each>
<xsl:for-each select="Request/Context/Retailer/code">
<xsl:variable name="var7_cur" select="."/>
<xsl:attribute name="Owner">
<xsl:value-of select="."/>
</xsl:attribute>
</xsl:for-each>
</Order>
</Query>
</OrderCancelRQ>
</xsl:template>
</xsl:stylesheet>